// src/components/ProjectCard.vue
<template>
  <div class="project-card group">
    <div class="relative overflow-hidden rounded-t-xl">
      <img 
        :src="project.image" 
        :alt="project.title" 
        class="w-full h-48 object-cover transition-transform duration-500 group-hover:scale-110"
      />
      
      <!-- Overlay on hover -->
      <div class="project-overlay">
        <h3 class="text-xl font-bold mb-4">
          {{ project.links.length > 0 ? 'Lien' + (project.links.length > 1 ? 's' : '') + ' du projet' : 'Pas de source pour ce projet' }}
        </h3>
        <div class="flex space-x-4">
          <a 
            v-for="(link, index) in project.links" 
            :key="index"
            :href="link.url" 
            target="_blank"
            class="project-icon"
            :aria-label="link.type"
          >
            <i :class="link.icon"></i>
          </a>
          <i v-if="project.links.length === 0" class="fa-solid fa-exclamation-circle text-3xl text-yellow-500"></i>
        </div>
      </div>
    </div>

    <div class="p-6 space-y-2">
      <h4 class="text-xl font-bold text-base-content group-hover:text-primary transition-colors">
        {{ project.title }} / {{ project.year }}
      </h4>
      <p class="text-base-content/60 text-sm">{{ project.description }}</p>
    </div>
  </div>
</template>

<script setup>
defineProps({
  project: {
    type: Object,
    required: true
  }
})
</script>

<style scoped>
.project-card {
  @apply bg-base-200 overflow-hidden shadow-xl hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-2 border-2 border-base-300 hover:border-primary;
  border-radius: var(--radius-box);
}

.project-overlay {
  @apply absolute inset-0 flex flex-col items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300;
  background-color: rgba(10, 14, 39, 0.95);
}

.project-icon {
  @apply w-12 h-12 bg-primary hover:bg-secondary rounded-full flex items-center justify-center text-primary-content text-xl transition-all duration-300 transform hover:scale-110;
}
</style>

// src/components/molecules/ProjectCard.tsx
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { ExternalLink } from 'lucide-react'
import { SiGithub } from '@icons-pack/react-simple-icons'
import type { Project } from '@/types/project'

interface ProjectCardProps {
  project: Project
}

export default function ProjectCard({ project }: ProjectCardProps) {
  const { t } = useTranslation()
  const imageUrl = project.image_url
    ? `/project-images/${project.image_url.split('/').pop()}`
    : null

  const skills = project.project_skills?.map((ps) => ps.skills) ?? []

  return (
    <div className="card bg-base-200 shadow-md hover:shadow-xl transition-shadow duration-300 h-full">
      <Link to={`/projects/${project.id}`} className="block">
        {imageUrl && (
          <figure className="h-48 overflow-hidden">
            <img
              src={imageUrl}
              alt={project.title}
              className="w-full h-full object-cover hover:scale-105 transition-transform duration-300"
              loading="lazy"
            />
          </figure>
        )}
        <div className="card-body gap-3 pb-2">
          <div className="flex items-start justify-between gap-2">
            <h3 className="card-title text-base-content text-lg">{project.title}</h3>
            {project.featured && (
              <span className="badge badge-primary badge-sm shrink-0">{t('projects.featured')}</span>
            )}
          </div>
          {project.year && (
            <span className="text-base-content/50 text-sm">{project.year}</span>
          )}
          <p className="text-base-content/70 text-sm flex-1">{project.description}</p>
        </div>
      </Link>

      <div className="card-body pt-0 gap-3">
        {skills.length > 0 && (
          <div className="flex flex-wrap gap-1">
            {skills.map((skill) => (
              <Link
                key={skill.id}
                to={`/skills/${skill.id}`}
                onClick={(e) => e.stopPropagation()}
                className="flex items-center gap-1 badge badge-ghost badge-sm hover:badge-primary transition-colors"
              >
                {skill.icon && <img src={skill.icon} alt={skill.name} width={12} height={12} />}
                <span>{skill.name}</span>
              </Link>
            ))}
          </div>
        )}

        <div className="card-actions justify-end">
          {project.github_url && (
            <a
              href={project.github_url}
              target="_blank"
              rel="noopener noreferrer"
              onClick={(e) => e.stopPropagation()}
              className="btn btn-outline btn-sm gap-2"
            >
              <SiGithub size={14} />
              {t('projects.viewGithub')}
            </a>
          )}
          {project.url && (
            <a
              href={project.url}
              target="_blank"
              rel="noopener noreferrer"
              onClick={(e) => e.stopPropagation()}
              className="btn btn-primary btn-sm gap-2"
            >
              <ExternalLink size={14} />
              {t('projects.viewLive')}
            </a>
          )}
        </div>
      </div>
    </div>
  )
}
