// src/components/Header.vue
<template>
  <header class="fixed top-0 left-0 w-full bg-base-200/95 backdrop-blur-sm shadow-lg z-50">
    <nav class="container mx-auto px-4 sm:px-6 lg:px-8 py-3 sm:py-4">
      <div class="flex items-center justify-between">
        <!-- Logo -->
        <a href="/" class="flex items-center space-x-3 hover:opacity-80 transition">
          <img src="@/assets/images/finnstay.gif" alt="Logo" class="w-8 h-8" />
          <span class="text-xl font-bold text-base-content">Gaspard Catry</span>
        </a>

        <!-- Desktop: Theme Switcher + Menu burger -->
        <div class="flex items-center space-x-4">
          <ThemeSwitcher />
          
          <button 
            @click="toggleMenu" 
            class="lg:hidden text-base-content text-2xl focus:outline-none"
            aria-label="Toggle menu"
          >
            <i :class="isMenuOpen ? 'fa-solid fa-times' : 'fa-solid fa-bars'"></i>
          </button>
        </div>

        <!-- Navigation -->
        <ul 
          class="nav-links"
          :class="{'active': isMenuOpen}"
        >
          <li v-for="item in navItems" :key="item.id">
            <a 
              :href="item.href" 
              @click="closeMenu"
              class="nav-link"
              :class="{'active-link': activeSection === item.id}"
            >
              {{ item.label }}
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import ThemeSwitcher from './molecules/ThemeSwitcher.vue'

const isMenuOpen = ref(false)
const activeSection = ref('home')

const navItems = [
  { id: 'home', label: 'Accueil', href: '#home' },
  { id: 'about', label: 'À propos', href: '#about' },
  { id: 'skills', label: 'Compétences', href: '#skills' },
  { id: 'education', label: 'Parcours', href: '#education' },
  { id: 'work', label: 'Projets', href: '#work' },
  { id: 'experience', label: 'Expérience', href: '#experience' },
  { id: 'contact', label: 'Contact', href: '#contact' },
]

const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value
}

const closeMenu = () => {
  isMenuOpen.value = false
}

const handleScroll = () => {
  const sections = navItems.map(item => document.querySelector(item.href))
  const scrollPosition = window.scrollY + 100

  sections.forEach((section, index) => {
    if (section && section.offsetTop <= scrollPosition && 
        section.offsetTop + section.offsetHeight > scrollPosition) {
      activeSection.value = navItems[index].id
    }
  })
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll)
})

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll)
})
</script>

<style scoped>
.nav-links {
  @apply hidden lg:flex space-x-8;
}

.nav-links.active {
  @apply flex flex-col absolute top-full left-0 w-full bg-base-200 shadow-lg py-4 space-x-0 space-y-2;
}

.nav-link {
  @apply transition-colors duration-300 font-medium;
  color: color-mix(in oklch, var(--color-base-content) 70%, transparent);
}

.nav-link:hover {
  color: var(--color-primary);
}

.nav-links.active .nav-link {
  padding: 0.5rem 1.5rem;
}

.active-link {
  @apply text-primary;
}
</style>

// src/components/organisms/Header.tsx
import { useState, useRef, useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import { Menu, X, Globe, ChevronDown, Check } from 'lucide-react'
import NavItem from '@/components/molecules/NavItem'
import ThemeSwitcher from '@/components/molecules/ThemeSwitcher'

const NAV_LINKS = [
  { to: '/', key: 'nav.home' },
  { to: '/projects', key: 'nav.projects' },
  { to: '/about', key: 'nav.about' },
  { to: '/contact', key: 'nav.contact' },
]

const LANGUAGES = [
  { code: 'fr', label: 'Français' },
  { code: 'en', label: 'English' },
]

function LanguageSwitcher() {
  const { i18n } = useTranslation()
  const [isOpen, setIsOpen] = useState(false)
  const dropdownRef = useRef<HTMLDivElement>(null)
  const current = LANGUAGES.find((l) => l.code === i18n.language) ?? LANGUAGES[0]

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setIsOpen(false)
      }
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  return (
    <div className="relative" ref={dropdownRef}>
      <button
        className="btn btn-ghost btn-sm gap-1.5"
        onClick={() => setIsOpen((o) => !o)}
        aria-label="Changer de langue"
        aria-expanded={isOpen}
      >
        <Globe size={15} />
        <span className="hidden sm:inline text-sm font-mono">{current.code.toUpperCase()}</span>
        <ChevronDown size={13} className={`transition-transform ${isOpen ? 'rotate-180' : ''}`} />
      </button>

      {isOpen && (
        <div className="absolute right-0 mt-2 w-36 bg-base-200 rounded-box shadow-lg z-50 py-1">
          {LANGUAGES.map((lang) => (
            <button
              key={lang.code}
              className={`w-full flex items-center gap-3 px-4 py-2 text-sm hover:bg-base-300 transition-colors ${
                i18n.language === lang.code ? 'text-primary font-semibold' : 'text-base-content'
              }`}
              onClick={() => {
                i18n.changeLanguage(lang.code)
                setIsOpen(false)
              }}
            >
              <span className="font-mono text-xs">{lang.code.toUpperCase()}</span>
              <span>{lang.label}</span>
              {i18n.language === lang.code && <Check size={14} className="ml-auto" />}
            </button>
          ))}
        </div>
      )}
    </div>
  )
}

export default function Header() {
  const { t } = useTranslation()
  const [mobileOpen, setMobileOpen] = useState(false)

  return (
    <header className="sticky top-0 z-40 bg-base-100/90 backdrop-blur-sm border-b border-base-300">
      <div className="max-w-5xl mx-auto px-4 h-16 flex items-center justify-between">
        {/* Logo */}
        <a href="/" className="flex items-center gap-2 font-mono font-bold text-primary text-lg">
          <img src="/favicon.gif" alt="Finn" className="w-8 h-8 rounded-full" />
          gaspard<span className="text-base-content/50">4i</span>
        </a>

        {/* Desktop nav */}
        <nav className="hidden md:flex items-center gap-1">
          {NAV_LINKS.map((link) => (
            <NavItem key={link.to} to={link.to} label={t(link.key)} />
          ))}
        </nav>

        {/* Controls */}
        <div className="flex items-center gap-1">
          <LanguageSwitcher />
          <ThemeSwitcher />

          {/* Mobile menu button */}
          <button
            className="btn btn-ghost btn-square btn-sm md:hidden"
            onClick={() => setMobileOpen((o) => !o)}
            aria-label="Menu"
          >
            {mobileOpen ? <X size={18} /> : <Menu size={18} />}
          </button>
        </div>
      </div>

      {/* Mobile menu */}
      {mobileOpen && (
        <nav className="md:hidden border-t border-base-300 bg-base-100 px-4 py-2 flex flex-col gap-1">
          {NAV_LINKS.map((link) => (
            <NavItem
              key={link.to}
              to={link.to}
              label={t(link.key)}
              onClick={() => setMobileOpen(false)}
            />
          ))}
        </nav>
      )}
    </header>
  )
}
